import {

    PAGE,

    COLORS,

    FONT

} from "../pdfTheme";
import { ensurePageSpace } from "../pdfPageHelper";

import {

    formatDate

} from "../pdfHelpers";

/* ==========================================================
   COVER PAGE
========================================================== */

export const drawCoverSection = (

    doc,

    report

) => {

    const {

        user,

        options

    } = report;

    doc.setFillColor(

        ...COLORS.primary

    );

    doc.rect(

        0,

        0,

        PAGE.width,

        PAGE.height,

        "F"

    );

    /* ---------- COMPANY ---------- */

    doc.setTextColor(255);

    doc.setFont(

        "helvetica",

        "bold"

    );

    doc.setFontSize(30);

    doc.text(

        user?.millName ||

        "Rice Mill ERP",

        PAGE.width / 2,

        55,

        {

            align: "center"

        }

    );

    /* ---------- REPORT TITLE ---------- */

    doc.setFontSize(22);

    doc.text(

        "BUSINESS PERFORMANCE REPORT",

        PAGE.width / 2,

        78,

        {

            align: "center"

        }

    );

    doc.setFont(

        "helvetica",

        "normal"

    );

    doc.setFontSize(12);

    doc.text(

        "Comprehensive Financial & Operational Report",

        PAGE.width / 2,

        90,

        {

            align: "center"

        }

    );

    /* ---------- DATE BOX ---------- */

    doc.setFillColor(255);

    doc.roundedRect(

        35,

        120,

        140,

        45,

        4,

        4,

        "F"

    );

    doc.setTextColor(

        ...COLORS.heading

    );

    doc.setFont(

        "helvetica",

        "bold"

    );

    doc.setFontSize(14);

    doc.text(

        "Reporting Period",

        PAGE.width / 2,

        135,

        {

            align: "center"

        }

    );

    doc.setFont(

        "helvetica",

        "normal"

    );

    doc.setFontSize(12);

    doc.text(

        `${formatDate(

            options.fromDate

        )}   to   ${formatDate(

            options.toDate

        )}`,

        PAGE.width / 2,

        148,

        {

            align: "center"

        }

    );

    /* ---------- GENERATED ---------- */

    doc.setTextColor(255);

    doc.setFontSize(11);

    doc.text(

        `Generated On : ${new Date().toLocaleString()}`,

        PAGE.width / 2,

        215,

        {

            align: "center"

        }

    );

    /* ---------- FOOTER ---------- */

    doc.setFont(

        "helvetica",

        "bold"

    );

    doc.setFontSize(14);

    doc.text(

        "Generated by Rice Mill ERP",

        PAGE.width / 2,

        275,

        {

            align: "center"

        }

    );

};